### PR TITLE
update build system to uv and remove versioneer

### PR DESCRIPTION
**Pull request by Eldolfin**
Hello! Pygment-tiger doesn't build on python 3.12, probably because the versioneer script was not updated in a while
```
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
  × Failed to build `/home/oscar/Prog/pygments-tiger`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_sdist` failed (exit status: 1)
      hint: This usually indicates a problem with the package or the build environment.
```

This PR simplifies the repo by removing all the unnecessary files and using uv as the "build system"

### CODE REVIEW

**Comment by Eldolfin** [comment]
I will redo the MR on gitlab instead
